"""
Auto-emit the wet-lab recipe for a compiled design.

The protocol is parameterised by the design (scaffold, number of staples, folding
buffer, anneal ramp) and is consistent with the canonical scaffolded-origami
protocols:
  * Rothemund, Nature 440:297 (2006)
  * Castro et al., "A primer to scaffolded DNA origami," Nature Methods 8:221 (2011)
  * Wagenbauer et al. / Dietz lab folding-buffer + ramp practice.
The same ramp is what the Arduino/PID thermocycler firmware executes
(see hardware/firmware/thermocycler.ino).
"""

from __future__ import annotations


def anneal_ramp(t_hot=90, t_cold=20, hold_hot_min=5, total_min=120, steps=14):
    """Linear cool ramp as a list of (temperature_C, minutes_at_step)."""
    per = total_min / steps
    ramp = [(t_hot, hold_hot_min)]
    for k in range(1, steps + 1):
        t = t_hot - (t_hot - t_cold) * k / steps
        ramp.append((round(t, 1), round(per, 1)))
    return ramp


def emit_screen(design: dict,
                mg_grid=(5, 8, 12.5, 16, 20),
                strategies=("ramp 90->20 (2h)", "ramp 65->25 (16h)",
                            "isothermal 50C", "isothermal 55C", "isothermal 60C")) -> str:
    """Auto-emit the per-design folding screen. Yield on a NEW shape is set mostly by
    MgCl2 x thermal strategy (Castro 2011; Wagenbauer 2017), so the compiler hands you a
    ready grid: one well per (MgCl2 x strategy), the plate map, and the exact host_ramp /
    setpoint to run for each. Pick the condition that gives the tightest gel band."""
    d = design
    rows = []
    well = 0
    cols = "ABCDEFGH"
    for s_i, strat in enumerate(strategies):
        for mg in mg_grid:
            r = cols[s_i % len(cols)]
            c = list(mg_grid).index(mg) + 1
            rows.append(f"| {r}{c} | {mg} | {strat} |")
            well += 1
    table = "\n".join(rows)
    return f"""# Folding screen - {d['design_name']}

Run this {len(rows)}-condition screen ONCE on a new design; read the winner off the gel
(tightest, fastest single band vs the scaffold-only lane). Then fold production batches
at the winning MgCl2 x strategy.

Each well: scaffold {d.get('scaffold_nM', 20)} nM + staples {d.get('staple_excess', 10)}x
in 1x TAE + the row's MgCl2, ~20 uL.

| Well | MgCl2 (mM) | Thermal strategy |
|------|-----------|------------------|
{table}

How to run each strategy on the rig (hardware/firmware):
- `ramp ...`  -> `python hardware/firmware/host_ramp.py --design design.json --port <COM>`
  (edit `--t-hot/--t-cold/--anneal-min` when you recompile, or step a sous-vide bath).
- `isothermal T` -> hold the block at T (firmware `SET <T>`) for 1-4 h, then cool.

Gel-score every well together (run cold, 1x TAE + ~11 mM MgCl2, 60-90 V). The
condition with the sharpest monomer band wins.
"""


def emit_protocol(design: dict) -> str:
    d = design
    ramp = d.get("anneal_ramp") or anneal_ramp()
    scaffold_nM = d.get("scaffold_nM", 20)
    excess = d.get("staple_excess", 10)
    staple_nM = scaffold_nM * excess
    n_staples = d["n_staples"]
    mg_mM = d.get("mg_mM", 12.5)
    vol_uL = d.get("reaction_uL", 50)

    ramp_rows = "\n".join(
        f"| {i} | {t:>5} | {m:>4} |" for i, (t, m) in enumerate(ramp)
    )
    total_h = round(sum(m for _, m in ramp) / 60.0, 1)

    syn = ""
    if d.get("synthetic_scaffold"):
        syn = ("\n> ⚠️ **This recipe was compiled against the SYNTHETIC fallback "
               "scaffold.** Run `python -m molsynth fetch-scaffold` and recompile to "
               "emit staples matched to real M13mp18 before ordering oligos.\n")

    return f"""# Wet-lab protocol — {d['design_name']}

_Auto-generated by Molecular Synth v0 compiler. Output = a DNA-origami nanostructure
(~{d.get('approx_nm', 'tens of')} nm), not a macroscopic object. See README scope line._
{syn}
## 0. What you are making
- Target shape: **{d['shape']}** rendered as a wireframe DNA origami.
- Scaffold: **{d['scaffold_name']}** ({d['scaffold_len_used']} nt used of {d.get('scaffold_total', '?')}).
- **{n_staples}** staple oligos, {d['total_staple_bases']} nt total to synthesise.

## 1. Order (see /bom for live links + prices)
1. **Scaffold ssDNA** — {d['scaffold_name']} (e.g. NEB N4040 M13mp18), resuspend/quantify to a known nM.
2. **Staple oligos** — order the {n_staples} sequences in `staples.csv`. For ~200 sequences,
   IDT **oPools** (pooled synthesis) is far cheaper per base than a 96-well plate; either works.
3. **Folding buffer (FOB)** — 1× TAE + **{mg_mM} mM MgCl₂** (40 mM Tris, 20 mM acetic acid,
   1 mM EDTA, {mg_mM} mM MgCl₂). Nuclease-free water throughout.

## 2. Assemble the folding reaction ({vol_uL} µL)
| Component | Final conc. |
|-----------|-------------|
| Scaffold ({d['scaffold_name']}) | {scaffold_nM} nM |
| Each staple (pooled) | {staple_nM} nM ({excess}× excess) |
| MgCl₂ | {mg_mM} mM |
| 1× TAE | buffer |

Mix on ice, vortex gently, spin down. Aliquot into a PCR tube.

## 3. Anneal (thermocycler / PID block — runs ~{total_h} h)
Run this ramp on the repurposed Peltier/PID thermocycler (hardware/firmware/thermocycler.ino).
A sous-vide bath stepped manually, or any programmable thermocycler, also works.

| Step | Temp (°C) | Hold (min) |
|------|-----------|------------|
{ramp_rows}

Then hold at {ramp[-1][0]} °C until you remove the tube. Slower ramps (extend total time
to 16–48 h, or narrow the window to 65→25 °C) raise yield for stiff/3D designs.

## 4. Verify the fold (DIY agarose gel — hardware/cad/gel_box)
1. Cast a **1.5–2 % agarose** gel in 1× TAE + {mg_mM} mM MgCl₂ (Mg in the *gel and running
   buffer* keeps origami intact).
2. Load 10 µL folding reaction + loading dye; include a DNA ladder and a scaffold-only lane.
3. Run **~60–90 V, 1.5–3 h**, gel box on ice or in a cold room (heat denatures origami).
4. Stain with GelRed/SYBR Safe; image on the blue-LED transilluminator.
   **Well-folded origami runs as one tight band migrating differently from the scaffold-only
   lane**; smearing/ladders = misfolding or aggregation → slow the ramp or retune Mg.

## 5. (Optional) Purify
PEG precipitation or a 100 kDa spin filter removes excess staples before hardening/imaging.

## 6. (Optional) Harden — DNA → silica (sol–gel)
To convert the soft template into a rigid silica replica (Liu 2018 Nature; Nguyen 2019
Angew. Chem.): incubate purified origami with an aminosilane (TMAPS/APTES) then TEOS in
the Mg buffer for ~1–4 days at room temperature; the prehydrolysed silica condenses on the
DNA backbone. **Do this in a fume hood** (TEOS/alcohol). This is the demonstrated route to a
mechanically robust copy. ALD metal-oxide coating (TiO₂/ZnO/Al₂O₃) is an alternative but
needs a vacuum reactor — out of the desktop budget; treat as a service step.

## 7. (Optional) Atomic-resolution check
The DIY STM (hardware/cad/stm) resolves the atomic lattice of HOPG graphite — it is the rig's
atomic-resolution *capability demonstrator*, not a direct origami imager (soft, hydrated DNA
is not STM-friendly). Use the gel for routine origami QC.

---
_Honest scope: this protocol yields ~10⁹–10¹² copies of a single ~{d.get('approx_nm','tens of')} nm
nanostructure per picomole-scale reaction. It does not yet build macroscopic parts._
"""
